# Stage client buid

FROM node:latest as base

WORKDIR /app/client

COPY client/package*.json ./

RUN NODE_ENV=development npm ci

FROM base as build 

WORKDIR /app/client

COPY client/src ./src

COPY client/dist ./dist

RUN npm run build

FROM golang:1.19 as backend

# RUN mkdir /app

# ADD . /app

WORKDIR /app/backend

COPY backend-server/go.mod backend-server/go.sum ./

RUN go mod download

COPY backend-server ./

RUN CGO_ENABLED=0 GOOS=linux go build -o main

FROM golang:1.19

WORKDIR /app

COPY --from=build /app/client/dist ./client/dist

COPY --from=backend /app/backend/main ./ 

CMD [ "./main" ]