# Stage client buid

FROM node:latest as base

WORKDIR /app/client

COPY ./client/package*.json .

COPY ./client/public ./public

COPY ./client/src ./src

RUN NODE_ENV=development npm ci

FROM base as build    

RUN npm run build

FROM golang:1.19 as backend

RUN mkdir /app

ADD . /app

WORKDIR /app

# COPY go.mod go.sum ./

# RUN go mod download

# COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o main

FROM golang:1.19

WORKDIR /app

COPY --from=base /app/client/dist ./client/dist

COPY --from=backend /app/backend/main ./ 

CMD [ "./main" ]

